### PR TITLE
Fixed typescript typings

### PR DESCRIPTION
**Pull request by iyegoroff**
## Motivation

Was unable to import interfaces from index.d.ts

## Test Plan

Import picker and its interfaces in typescript:
`import ImagePicker, {Response} from 'react-native-image-picker';`

### CODE REVIEW

**Comment by AntonShevel** [comment]
Would be great to have it merged

**Comment by pascaloliv** [comment]
@AntonShevel : Same. Would be great. Changes looks good.

**Comment by mcabs3** [comment]
I would love these changes to be added too!

**Comment by gablorquet** [comment]
Bumping this. In the current state of the typings, in their current state, typings are unusable as they infer a default export.

**Comment by iamolegga** [comment]
It's almost 2 years of this pr! 😀

**Comment by Johan-dutoit** [comment]
Closing PR as this is no longer relevant.

Besides you can do the following in a TypeScript project:
`import ImagePicker, { ImagePickerResponse } from 'react-native-image-picker';`

**Pull request closed without merging**
