### PR TITLE
Make sure the calls are execute on the main thread

### PR DESCRIPTION
**Pull request by andrei-tofan**
Thanks for submitting a PR! Please read these instructions carefully:

- [x] Explain the **motivation** for making this change.
- [x] Provide a **test plan** demonstrating that the code is solid.
- [x] Match the **code formatting** of the rest of the codebase.
- [x] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)
UIKit complains when  ImagePickerController not being called from main thread. 
To fix this I've added this method recommended in the docs:
http://facebook.github.io/react-native/docs/native-modules-ios.html#threading

What existing problem does the pull request solve?
#1199 (updated)

## Test Plan (required)
Not need, no business logic changed, all test pass.

### CODE REVIEW

**Comment by Johan-dutoit** [comment]
How is this different from the PR you mentioned: #1205?

**Comment by andrei-tofan** [comment]
Hi @Johan-dutoit, I've updated the issue it fixes, accidentally pasted the wrong issue, I think #1205 tries to fix the same issue, but my fix is a bit more simple and also follows the pattern from `RCT_EXPORT_METHOD(showImagePicker:(NSDictionary *)options callback:(RCTResponseSenderBlock)callback)`.

**Comment by kmh0237** [comment]
This worked for me on iOS when I pulled it down.  It also fixed both the original issue and doesn't cause the OK button issue plauging https://github.com/react-native-community/react-native-image-picker/pull/1205.  This should be merged ASAP, camera functionality is incredibly slow on iOS without this fix.

**Comment by EricWiener** [comment]
Can this please be merged

**Comment by fedenelli** [comment]
Just tested it and works great. Hope this gets merged soon.

**Comment by airowe** [comment]
Any chance of this getting merged?

**Comment by rednebmas** [comment]
@Johan-dutoit or @janicduplessis can this please be merged? It's an extremely simple fix for a pretty bad bug (5-10 second delay for opening the image picker).

**Comment by bartzy** [comment]
When a release with these changes is expected?

**Comment by rednebmas** [comment]
This was in 2.3.2

**Comment by bartzy** [comment]
@rednebmas Ah, I see. Thanks!

There's still some slowness sometimes on iOS, especially when opening the picker for the first time (takes 2-3 seconds), so I thought it might be related.

**Comment by andredewaard** [comment]
Anyone also experience that the app is not responsive for 1/2 seconds after selecting an image?

**Pull request merged**
